version: '3.3'
services:
  #backend:
  #  build: ../proto/app.py
  #  ports:
  #    - 9000:9000
  proxy:
    image: envoyproxy/envoy-alpine:v1.14.1
    environment:
      NODE_ENV: development
      loglevel: debug
    ports:
      - 8081:8081
      - 9900:9900
    extra_hosts: # <---- here
      - localhost:192.168.205.128
      - or-vitualhost.local:192.168.205.128
    networks:
      - envoymesh
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
networks:
  envoymesh: {}