version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    restart: always

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5001:5001"
    restart: always

  register:
    container_name: register
    build: ./register
    ports:
      - "5002:5002"
    restart: always

  proxy:
      image: envoyproxy/envoy-alpine:v1.14.1
      build: ./envoy
      environment:
        NODE_ENV: development
        loglevel: debug
      ports:
        - 8080:8080
        - 9901:9901
      networks:
        - envoymesh
      volumes:
        - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml

  mongodb-student:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./data:/data/db


networks:
  envoymesh: {}


      